variable "appgw_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "appgw_sku_name" {}
variable "appgw_sku_tier" {}
variable "appgw_sku_capacity" {}
variable "gateway_ip_configuration_name" {}
variable "gateway_ip_configuration_subnet_id" {}
variable "frontend_port_name" {}
variable "frontend_port_port" {}
variable "frontend_ip_configuration_name" {}
variable "public_ip_address_id" {}
variable "backend_address_pool_name" {}
variable "backend_http_settings_name" {}
variable "backend_http_settings_cookie_based_affinity" {}
variable "backend_http_settings_path" {}
variable "backend_http_settings_port" {}
variable "backend_http_settings_protocol" {}
variable "backend_http_settings_request_timeout" {}
variable "http_listener_name" {}
variable "http_listener_protocol" {}
variable "request_routing_rule_name" {}
variable "request_routing_rule_priority" {}
variable "request_routing_rule_type" {}