variable "kv_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "enabled_for_disk_encryption" {}
variable "soft_delete_retention_days" {}
variable "purge_protection_enabled" {}
variable "sku_name" {}
variable "key_permissions" {}
variable "secret_permissions" {}
variable "storage_permissions" {}